version: '3.7'
services:
  rabbitmq:
    restart: always  
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.50'
        reservations:
          memory: 512M
          cpus: '0.25'